'use client'

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION';
export const SHOW_SUCCESS_NOTIFICATION_FOR_ADMIN = 'SHOW_SUCCESS_NOTIFICATION_FOR_ADMIN';
export const SHOW_ERROR_NOTIFICATION_FOR_ADMIN = 'SHOW_ERROR_NOTIFICATION_FOR_ADMIN';
export const HIDE_NOTIFICATION_FOR_ADMIN = 'HIDE_NOTIFICATION_FOR_ADMIN';
export const COUNTRY_CODE = "in";
export const SHOW_SUCCESS_NOTIFICATION_FOR_AUTH_USER = "SHOW_SUCCESS_NOTIFICATION_FOR_AUTH_USER";
export const SHOW_ERROR_NOTIFICATION_FOR_AUTH_USER = "SHOW_ERROR_NOTIFICATION_FOR_AUTH_USER";
export const HIDE_NOTIFICATION_FOR_AUTH_USER = "HIDE_NOTIFICATION_FOR_AUTH_USER";


